[project]
name = "regexplanet-python3"
version = "0.1.0"
description = "Python3 backend for RegexPlanet"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "hypercorn>=0.17.3",
    "quart>=0.19.6",
]
